package cli

func BashCompletionScript() string {
	return `# helm shell completion for bash (generated by "helm completion bash")
# Install: helm completion bash | sudo tee /etc/bash_completion.d/helm
#     or: source <(helm completion bash)

_helm()
{
	local helm_bin
	helm_bin="$(command -v helm 2>/dev/null)" || return

	mapfile -t COMPREPLY < <(
		COMP_CWORD="${COMP_CWORD}" "${helm_bin}" __complete -- "${COMP_WORDS[@]}" 2>/dev/null
	)
}

complete -F _helm helm
`
}
